# Generated by Django 2.2.6 on 2020-04-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('done', 'done')], default='new', max_length=20)),
                ('linked_id', models.IntegerField(null=True)),
            ],
            bases=(models.Model, object),
        ),
    ]
